name: Deploy Inference

on:
  push:
    branches: [main]
    paths: ['inference/**']

jobs:
  deploy-inference:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.18'

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install caprover
        run: sudo npm install -g caprover

      - name: Create tar
        run: |
          # Change the dockerfilePath to use ws.Dockerfile instead
          sed -i 's/"dockerfilePath": ".\/Dockerfile"/"dockerfilePath": ".\/inference.Dockerfile"/g' ./captain-definition

          tar -cvf ./deploy.tar --exclude='node_modules' --exclude='.git' --exclude='.next' *

      - name: Deploy
        run: caprover deploy -h ${{ secrets.CAPROVER_SERVER_PROD }} -p ${{ secrets.CAPROVER_PASSWORD_PROD }} -a chatexto-inference -t ./deploy.tar